[workspace]
authors = ["Sina Shamsian <snshamsi@uci.edu>"]
channels = ["conda-forge"]
name = "example"
platforms = ["osx-arm64","linux-64","win-64"]
version = "0.1.0"

[tasks]
lab = { cmd = "jupyter lab", description = "Launch JupyterLab" }
start = { depends-on = [{ task = "lab" }], description = "Start exploring the Pixi project" }

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"
